### ISSUE TITLE
Email confirmation of new user could use some spacing for readability

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#108]
In GitLab by @Khiggins42 on Apr 18, 2018, 15:29

Expected: an email confirmation message with link, username and welcome text

Observed: the above, but a bit too densely packed

It'd be nice to have, at a minimum, some linefeeds as marked here:
![email-confirmation](/uploads/046943f553d1558cce98e37ce4214429/email-confirmation.png)

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jun 2, 2018, 13:00

assigned to @StephenCataldo

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jun 4, 2018, 13:02

mentioned in commit 29cf48d8f9a85101d75281294db48fbcdb112db2

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jun 4, 2018, 16:29

This affects all emails. Fixed by adding a filter.

**Comment by treasuretron** [comment]
In GitLab by @StephenCataldo on Jun 4, 2018, 17:21

mentioned in merge request !156

**Comment by treasuretron** [comment]
In GitLab by @Khiggins42 on Jun 11, 2018, 14:00

QA on prod

Confirmed formatting has more breathing room and looks good.

![Screen_Shot_2018-06-11_at_1.59.17_PM](/uploads/0dce062b025faf73538f8d5bf2d8e4ce/Screen_Shot_2018-06-11_at_1.59.17_PM.png)

**Comment by treasuretron** [comment]
In GitLab by @richbodo on Jun 15, 2018, 20:24

closed

**Comment by epaatdahlstrom** [comment]
The confirmation email can be simplifield to:

Test2020,

Thank you for registering at SpaceBase. Log in and set your password using the link below:

http://live-spacebasenz.pantheonsite.io/user/reset/993/1583896713/gRBUBvQQLdg-7-jBrJwe_43wLXdKhRzNKzEsdudJz7U

This link is only valid once.

Below information should be stated after they reset their password, and not in this email.

_**After setting your password, you will be able to log in at http://live-spacebasenz.pantheonsite.io/user in the future using:

username: Test2020
password: Your password**_

-- SpaceBase team
